import java.util.Arrays;
import java.util.HashMap;

/**
  Name: 
  E-mail address: 
  Course: 
  Section: 
  Assignment: 
  Date: 

  Template Author: Philip Chan
  Modify:
  1.  class/constructor name: ComputerPlayerFirst, eg. ComputerPlayerJohn
  2.  attribute _name: your name
  3.  makeAMove() method

  Description: My modified version of the computer player to play in the Tic-Tac-Toe tournament.

*/

public class ComputerPlayerSmartHash // **** use your first name
{
    private final String      _name = "Brayden Cheek";    // **** change it to your name
    private final char        _symbol;
    private int 			  turn = 0;
    private HashMap<String, int[]> moves = new HashMap<String, int[]>();
    
    
    public ComputerPlayerSmartHash(char symbol) // **** use your first name
    {
	_symbol = symbol;
	if (_symbol=='X') {
		moves.put("     O   ", new int[] {1, 1});
		moves.put("O   XO   ", new int[] {2, 1});
		moves.put("O   XOOX ", new int[] {0, 1});
		moves.put("         ", new int[] {1, 1});
		moves.put("O   X    ", new int[] {2, 2});
		moves.put("O   XO  X", new int[] {2, 1});
		moves.put("O O XO XX", new int[] {2, 0});
		moves.put("OO  XO X ", new int[] {0, 2});
		moves.put("OOX XO XO", new int[] {2, 0});
		moves.put("O   X  OX", new int[] {1, 2});
		moves.put("OO  XX OX", new int[] {1, 0});
		moves.put(" O       ", new int[] {1, 1});
		moves.put(" O  X   O", new int[] {1, 2});
		moves.put("OO  XX  O", new int[] {1, 0});
		moves.put("    X  O ", new int[] {0, 0});
		moves.put("X   X OO ", new int[] {2, 2});
		moves.put("    XOO  ", new int[] {2, 1});
		moves.put("  O XOOX ", new int[] {0, 1});
		moves.put("  O X    ", new int[] {2, 0});
		moves.put("  OOX X  ", new int[] {2, 1});
		moves.put("  OOX XXO", new int[] {0, 1});
		moves.put("OOXOXO X ", new int[] {2, 0});
		moves.put("    X   O", new int[] {0, 0});
		moves.put("X O X   O", new int[] {1, 2});
		moves.put("XOO XX  O", new int[] {1, 0});
		moves.put("       O ", new int[] {1, 1});
		moves.put("  O X  O ", new int[] {1, 2});
		moves.put("O O XX O ", new int[] {1, 0});
		moves.put("    XO   ", new int[] {0, 0});
		moves.put("X  OXO   ", new int[] {2, 2});
		moves.put("        O", new int[] {1, 1});
		moves.put(" OO XX  O", new int[] {1, 0});
		moves.put("X O X  O ", new int[] {2, 2});
		moves.put("    X O O", new int[] {2, 1});
		moves.put(" O  X OXO", new int[] {1, 2});
		moves.put("OO  XXOXO", new int[] {1, 0});
		moves.put("X   XO O ", new int[] {2, 2});
		moves.put("O        ", new int[] {1, 1});
		moves.put("O   X O  ", new int[] {1, 0});
		moves.put("O  XX O O", new int[] {1, 2});
		moves.put("X   X  OO", new int[] {2, 0});
		moves.put("XO  X XOO", new int[] {1, 0});
		moves.put("      O  ", new int[] {1, 1});
		moves.put("    X OO ", new int[] {2, 2});
		moves.put("  O X OOX", new int[] {0, 0});
		moves.put("X   XO  O", new int[] {0, 2});
		moves.put("X X XOO O", new int[] {0, 1});
		moves.put("    O    ", new int[] {0, 0});
		moves.put("X O O    ", new int[] {2, 0});
		moves.put("XOO O X  ", new int[] {1, 0});
		moves.put("O  OX   X", new int[] {2, 0});
		moves.put("O  OX XOX", new int[] {0, 2});
		moves.put("XO  O    ", new int[] {2, 1});
		moves.put("XO OO  X ", new int[] {1, 2});
		moves.put("XO OOX XO", new int[] {0, 2});
		moves.put("X O XO   ", new int[] {2, 2});
		moves.put("  O      ", new int[] {1, 1});
		moves.put("O O X    ", new int[] {0, 1});
		moves.put("OXO X  O ", new int[] {1, 2});
		moves.put("OXO XXOO ", new int[] {1, 0});
		moves.put("   OX    ", new int[] {0, 0});
		moves.put("XO OX    ", new int[] {2, 2});
		moves.put(" O  XO   ", new int[] {2, 2});
		moves.put(" O  XOO X", new int[] {0, 0});
		moves.put("X   O O  ", new int[] {0, 2});
		moves.put("X X O O O", new int[] {0, 1});
		moves.put(" O  X  O ", new int[] {1, 2});
		moves.put("OO  XX O ", new int[] {1, 0});
		moves.put("X   XOXOO", new int[] {1, 0});
		moves.put(" OO X    ", new int[] {0, 0});
		moves.put("XOO X   O", new int[] {1, 2});
		moves.put("XOOOXX  O", new int[] {2, 0});
		moves.put("  O XOX  ", new int[] {2, 2});
		moves.put("  O XOXOX", new int[] {0, 0});
		moves.put("O   X  O ", new int[] {1, 2});
		moves.put("X  OX O  ", new int[] {2, 2});
		moves.put("O  XX OO ", new int[] {1, 2});
		moves.put("X OOX    ", new int[] {2, 2});
		moves.put("XOO X  O ", new int[] {2, 2});
		moves.put("OO  X   X", new int[] {0, 2});
		moves.put("OOXOX   X", new int[] {1, 2});
		moves.put("  O X   O", new int[] {1, 2});
		moves.put("O O XX  O", new int[] {1, 0});
		moves.put(" OO XO  X", new int[] {0, 0});
		moves.put("O   X   O", new int[] {1, 2});
		moves.put(" O  X    ", new int[] {0, 0});
		moves.put("XO  X  O ", new int[] {2, 2});
		moves.put("XOX O O  ", new int[] {2, 1});
		moves.put("XOX OOOX ", new int[] {1, 0});
		moves.put("XO  X O  ", new int[] {2, 2});
		moves.put("   OX   O", new int[] {2, 1});
		moves.put("O  OX  XO", new int[] {0, 1});
		moves.put("O  OXX OX", new int[] {0, 2});
		moves.put("O  OXX  O", new int[] {2, 0});
		moves.put("OO OXXX O", new int[] {0, 2});
		moves.put(" O OXX  O", new int[] {2, 0});
		moves.put(" OOOXXX O", new int[] {0, 0});
		moves.put(" O  X OOX", new int[] {0, 0});
		moves.put("X  OX   O", new int[] {0, 1});
		moves.put("XXOOX   O", new int[] {2, 1});
		moves.put("    XO O ", new int[] {2, 2});
		moves.put(" O  XO OX", new int[] {0, 0});
		moves.put("    X O  ", new int[] {0, 2});
		moves.put("O X X O  ", new int[] {1, 0});
		moves.put("O XXX O O", new int[] {1, 2});
		moves.put("   OXO XO", new int[] {0, 1});
		moves.put("O O X   X", new int[] {0, 1});
		moves.put("OXO X O X", new int[] {2, 1});
		moves.put("   OXO   ", new int[] {2, 1});
		moves.put("   OXOOX ", new int[] {0, 1});
		moves.put("X   O   O", new int[] {0, 2});
		moves.put("XOX O   O", new int[] {2, 1});
		moves.put("XOX OO XO", new int[] {1, 0});
		moves.put("O O XOX X", new int[] {2, 1});
		moves.put("O  OX    ", new int[] {2, 0});
		moves.put("O  OXOX  ", new int[] {0, 2});
		moves.put("XOX XO  O", new int[] {2, 0});
		moves.put(" O  X O  ", new int[] {1, 2});
		moves.put("OO  XXO  ", new int[] {1, 0});
		moves.put("OO  X    ", new int[] {0, 2});
		moves.put("OOX XO   ", new int[] {2, 0});
		moves.put(" OO X X  ", new int[] {0, 0});
		moves.put("XOO XOX  ", new int[] {1, 0});
		moves.put("  OOX    ", new int[] {2, 1});
		moves.put("  OOX OX ", new int[] {0, 1});
		moves.put(" O  XXOO ", new int[] {1, 0});
		moves.put("  XOX O  ", new int[] {0, 0});
		moves.put("X XOXOO  ", new int[] {0, 1});
		moves.put("O O XO X ", new int[] {0, 1});
		moves.put("XO  X   O", new int[] {1, 0});
		moves.put("XO XXO  O", new int[] {2, 0});
		moves.put("   O     ", new int[] {1, 1});
		moves.put("   OX O  ", new int[] {0, 0});
		moves.put("X  OX OO ", new int[] {2, 2});
		moves.put("   OX OOX", new int[] {0, 0});
		moves.put("X O XX OO", new int[] {1, 0});
		moves.put("X  OX XOO", new int[] {0, 2});
		moves.put("XOO XXO O", new int[] {1, 0});
		moves.put("OOX XO  X", new int[] {2, 0});
		moves.put("OXO X   O", new int[] {2, 1});
		moves.put("O  OXOX X", new int[] {2, 1});
		moves.put("O  OXX O ", new int[] {2, 0});
		moves.put("O OOXXXO ", new int[] {0, 1});
		moves.put("X X XO OO", new int[] {0, 1});
		moves.put("O   XX OO", new int[] {1, 0});
		moves.put("X   O  O ", new int[] {0, 1});
		moves.put("XX OO  O ", new int[] {0, 2});
		moves.put("XX OXO  O", new int[] {0, 2});
		moves.put("OOXOX    ", new int[] {2, 0});
		moves.put("O O X X  ", new int[] {0, 1});
		moves.put("OXOOX X  ", new int[] {2, 1});
		moves.put("O  OX XO ", new int[] {0, 2});
		moves.put("XOO X O  ", new int[] {2, 2});
		moves.put("  O X O  ", new int[] {1, 2});
		moves.put("O O XXO  ", new int[] {1, 0});
		moves.put("  OOXOXX ", new int[] {2, 2});
		moves.put("   OX  O ", new int[] {2, 2});
		moves.put("   OXO OX", new int[] {0, 0});
		moves.put("  O X X O", new int[] {1, 2});
		moves.put("O O XXX O", new int[] {1, 0});
		moves.put(" O  XX OO", new int[] {1, 0});
		moves.put("  O X XO ", new int[] {1, 0});
		moves.put("  OXXOXO ", new int[] {0, 0});
		moves.put("    X  OO", new int[] {2, 0});
		moves.put("    XOXOO", new int[] {0, 2});
		moves.put("XX OX  OO", new int[] {0, 2});
		moves.put("  O XO   ", new int[] {2, 2});
		moves.put("O O XO  X", new int[] {0, 1});
		moves.put("OXOOXO  X", new int[] {2, 1});
		moves.put("X   OO   ", new int[] {1, 0});
		moves.put("XO XOO   ", new int[] {2, 0});
		moves.put("  X XOO  ", new int[] {0, 1});
		moves.put(" XX XOOO ", new int[] {0, 0});
		moves.put("XOO X    ", new int[] {2, 2});
		moves.put("O  OXO X ", new int[] {0, 1});
		moves.put(" O OX    ", new int[] {0, 0});
		moves.put("XO OX  O ", new int[] {2, 2});
		moves.put("O XXXOO  ", new int[] {2, 1});
		moves.put("O XXXOOXO", new int[] {0, 1});
		moves.put("O  OXXXOO", new int[] {0, 2});
		moves.put("X  OX  O ", new int[] {2, 2});
		moves.put("O OOX X  ", new int[] {0, 1});
		moves.put("OXOOXOX  ", new int[] {2, 1});
		moves.put(" OOOX XX ", new int[] {2, 2});
		moves.put("X O O X O", new int[] {1, 0});
		moves.put("OOX X   O", new int[] {2, 0});
		moves.put("X XOXO  O", new int[] {0, 1});
		moves.put("OXOOX XO ", new int[] {2, 2});
		moves.put("    XO  O", new int[] {0, 2});
		moves.put(" OX XO  O", new int[] {2, 0});
		moves.put("OOXXX O  ", new int[] {1, 2});
		moves.put("  OOX  OX", new int[] {0, 0});
		moves.put("O   X O X", new int[] {1, 0});
		moves.put("OO XX O X", new int[] {1, 2});
		moves.put("O   XXOO ", new int[] {1, 0});
		moves.put("XO  XO   ", new int[] {2, 2});
		moves.put("O OXX O X", new int[] {1, 2});
		moves.put("  X XOO O", new int[] {2, 1});
		moves.put(" OX XOOXO", new int[] {0, 0});
		moves.put("OO XX O  ", new int[] {1, 2});
		moves.put("O O XX OX", new int[] {1, 0});
		moves.put(" O OX  XO", new int[] {0, 2});
		moves.put("OOXOX  XO", new int[] {2, 0});
		moves.put("O   XO XO", new int[] {0, 1});
		moves.put("OXO XO OX", new int[] {2, 0});
		moves.put("XO XX O O", new int[] {1, 2});
		moves.put("  O XX OO", new int[] {1, 0});
		moves.put("OO  XO  X", new int[] {0, 2});
		moves.put("OOX XO OX", new int[] {2, 0});
		moves.put(" OO XXO  ", new int[] {1, 0});
		moves.put(" OX X O  ", new int[] {1, 2});
		moves.put(" OX XXO O", new int[] {1, 0});
		moves.put("  OOXOX X", new int[] {2, 1});
		moves.put(" O  XXO O", new int[] {1, 0});
		moves.put("X   XOO  ", new int[] {2, 2});
		moves.put("  OOX  XO", new int[] {0, 1});
		moves.put("  XOXO  O", new int[] {2, 0});
		moves.put("O   XXOOX", new int[] {1, 0});
		moves.put("O  OX X O", new int[] {0, 2});
		moves.put("XOOOX    ", new int[] {2, 2});
		moves.put(" OX XXOO ", new int[] {1, 0});
		moves.put("OOX XXO  ", new int[] {1, 0});
		moves.put("  O XXXOO", new int[] {1, 0});
		moves.put("X  OX O O", new int[] {2, 1});
		moves.put("XO OX OXO", new int[] {0, 2});
		moves.put("X O XXO O", new int[] {1, 0});
		moves.put("X  XOO  O", new int[] {2, 0});
		moves.put("  X X O O", new int[] {2, 1});
		moves.put("  X XOOXO", new int[] {0, 1});
		moves.put("O X XO  O", new int[] {2, 0});
		moves.put("OOXOXO  X", new int[] {2, 0});
		moves.put("XX OX O O", new int[] {0, 2});
		moves.put(" OXOX OXO", new int[] {0, 0});
		moves.put("X XOO   O", new int[] {0, 1});
		moves.put("XO OX   O", new int[] {2, 0});
		moves.put("XO OX XOO", new int[] {0, 2});
		moves.put(" OO XX O ", new int[] {1, 0});
		moves.put("X  OXOO  ", new int[] {2, 2});
		moves.put("X  OO    ", new int[] {1, 2});
		moves.put("X  OOX O ", new int[] {0, 1});
		moves.put("XXOOOX O ", new int[] {2, 0});
		moves.put("  OOXO X ", new int[] {0, 1});
		moves.put("    XOOXO", new int[] {0, 1});
		moves.put(" OOXX XO ", new int[] {1, 2});
		moves.put("XOOOX X O", new int[] {1, 2});
		moves.put("   OX OXO", new int[] {0, 1});
		moves.put(" O  XOOX ", new int[] {0, 0});
		moves.put("XOO XOOX ", new int[] {2, 2});
		moves.put("  OOXXO  ", new int[] {0, 0});
		moves.put("X OOXXOO ", new int[] {2, 2});
		moves.put("XOO X XO ", new int[] {1, 0});
		moves.put("X OOXXO O", new int[] {2, 1});
		moves.put("XOO XO   ", new int[] {2, 2});
		moves.put("  X X OO ", new int[] {2, 2});
		moves.put("O X X OOX", new int[] {1, 2});
		moves.put("OXOOX    ", new int[] {2, 1});
		moves.put("O OOX X X", new int[] {2, 1});
		moves.put("X   X O O", new int[] {2, 1});
		moves.put("X O X OXO", new int[] {0, 1});
		moves.put("  O X XOO", new int[] {1, 2});
		moves.put("O O XXXOO", new int[] {1, 0});
		moves.put("O XXX OO ", new int[] {1, 2});
		moves.put(" OX X OOX", new int[] {1, 2});
		moves.put("    XOOOX", new int[] {0, 0});
		moves.put("X OXOO   ", new int[] {2, 0});
		moves.put("O  XX OOX", new int[] {1, 2});
		moves.put("XO OX O  ", new int[] {2, 2});
		moves.put("O OXX O  ", new int[] {1, 2});
		moves.put("  O X OXO", new int[] {0, 1});
		moves.put("X  OX OXO", new int[] {0, 1});
		moves.put("  OXX XOO", new int[] {1, 2});
		moves.put("  O XXOO ", new int[] {1, 0});
		moves.put("X X OO  O", new int[] {0, 1});
		moves.put(" OO XOX X", new int[] {2, 1});
		moves.put("XXO O  O ", new int[] {2, 0});
		moves.put("XXOOO XO ", new int[] {1, 2});
		moves.put("XO OOX   ", new int[] {2, 1});
		moves.put("  O XXO O", new int[] {1, 0});
		moves.put("XO XX  OO", new int[] {1, 2});
		moves.put("OXO X O  ", new int[] {2, 1});
		moves.put("OXO X  OX", new int[] {1, 2});
		moves.put("OXOOXX OX", new int[] {2, 0});
		moves.put("O   X XOO", new int[] {0, 2});
		moves.put("OXX XOO  ", new int[] {2, 1});
		moves.put("O   XO OX", new int[] {2, 0});
		moves.put("OO  XOXOX", new int[] {0, 2});
		moves.put("XOO X X O", new int[] {1, 0});
		moves.put("O OOX  X ", new int[] {0, 1});
		moves.put("  O XO OX", new int[] {0, 0});
		moves.put(" O OXO X ", new int[] {2, 2});
		moves.put(" O OXOOXX", new int[] {0, 0});
		moves.put(" XXOXOO  ", new int[] {0, 0});
		moves.put("OO OXO XX", new int[] {2, 0});
		moves.put("X OOX OXO", new int[] {0, 1});
		moves.put("OOX X O X", new int[] {1, 2});
		moves.put("XOOXX   O", new int[] {1, 2});
		moves.put(" O  X XOO", new int[] {0, 2});
		moves.put("  OOXXXOO", new int[] {0, 0});
		moves.put("X XOO O  ", new int[] {0, 1});
		moves.put("XO  X OXO", new int[] {1, 2});
		moves.put("XOO XXOXO", new int[] {1, 0});
		moves.put("OXO XOX  ", new int[] {2, 1});
		moves.put(" OOOX  X ", new int[] {0, 0});
		moves.put("XOOOXO X ", new int[] {2, 2});
		moves.put(" OXOXXO  ", new int[] {2, 2});
		moves.put("O   X OXO", new int[] {0, 1});
		moves.put(" O OXXO  ", new int[] {0, 0});
		moves.put("XO OXXOO ", new int[] {2, 2});
		moves.put("OXOOXX O ", new int[] {2, 0});
		moves.put("XOO O  X ", new int[] {2, 0});
		moves.put("XOOOO XX ", new int[] {2, 2});
		moves.put("X  OXOOXO", new int[] {0, 1});
		moves.put("XO  XOOXO", new int[] {0, 2});
		moves.put("  OOXXX O", new int[] {2, 1});
		moves.put(" OOOXXXXO", new int[] {0, 0});
		moves.put(" O OXO  X", new int[] {0, 0});
		moves.put("OO OX X X", new int[] {2, 1});
		moves.put("OXO X XO ", new int[] {1, 2});
		moves.put("OXOOXXXO ", new int[] {2, 2});
		moves.put("  OOXO  X", new int[] {0, 0});
		moves.put("O   X OOX", new int[] {1, 0});
		moves.put("OO XX OOX", new int[] {1, 2});
		moves.put("X OOOX   ", new int[] {2, 0});
		moves.put("XOOOOXX  ", new int[] {2, 1});
		moves.put("OOX X O  ", new int[] {1, 0});
		moves.put("OOXXX OO ", new int[] {1, 2});
		moves.put("  OOXX  O", new int[] {2, 1});
		moves.put(" OOOXX XO", new int[] {0, 0});
		moves.put("X O OOX  ", new int[] {1, 0});
		moves.put("O  XXOO  ", new int[] {2, 1});
		moves.put("O OXXOOX ", new int[] {0, 1});
		moves.put(" O OX  OX", new int[] {0, 0});
		moves.put("  X XOOOX", new int[] {0, 0});
		moves.put("OXO X X O", new int[] {2, 1});
		moves.put("X O X XOO", new int[] {1, 0});
		moves.put("  OOXXOXO", new int[] {0, 1});
		moves.put("OXOOX X O", new int[] {2, 1});
		moves.put("XOOOX X  ", new int[] {2, 2});
		moves.put("XO OXOX O", new int[] {0, 2});
		moves.put("OOXXX O O", new int[] {1, 2});
		moves.put("O   XOOXX", new int[] {0, 1});
		moves.put("O  OX  OX", new int[] {2, 0});
		moves.put("O OOX XOX", new int[] {0, 1});
		moves.put("XO  OO X ", new int[] {1, 0});
		moves.put("XO XOO XO", new int[] {2, 0});
		moves.put("O X XOOXO", new int[] {0, 1});
		moves.put("X  XOO O ", new int[] {2, 0});
		moves.put("  XOX OOX", new int[] {1, 2});
		moves.put("O O XOXOX", new int[] {0, 1});
		moves.put("OOX X  O ", new int[] {2, 0});
		moves.put("OXO XX OO", new int[] {1, 0});
		moves.put("XO OXO   ", new int[] {2, 2});
		moves.put("X OOXX  O", new int[] {2, 1});
		moves.put("XOOOXX XO", new int[] {2, 0});
		moves.put("OXOOX   X", new int[] {2, 1});
		moves.put("X X OOO  ", new int[] {0, 1});
		moves.put("XO OXXOXO", new int[] {0, 2});
		moves.put(" OOOXO XX", new int[] {2, 0});
		moves.put("OXO XXOOX", new int[] {1, 0});
		moves.put("XO  O OX ", new int[] {0, 2});
		moves.put("XX OOXOO ", new int[] {0, 2});
		moves.put("  OOXX O ", new int[] {0, 0});
		moves.put("X OOXX OO", new int[] {2, 0});
		moves.put("O OOX XX ", new int[] {2, 2});
		moves.put("X X O OO ", new int[] {0, 1});
		moves.put("  XOXOOXO", new int[] {0, 1});
		moves.put("XOOOXXO  ", new int[] {2, 2});
		moves.put("OO OX XOX", new int[] {0, 2});
		moves.put(" O OXX O ", new int[] {2, 2});
		moves.put(" OOOXX OX", new int[] {0, 0});
		moves.put("O OOXX XO", new int[] {0, 1});
		moves.put("X OOX O  ", new int[] {2, 2});
		moves.put("XOXOO OX ", new int[] {1, 2});
		moves.put("O X X OXO", new int[] {0, 1});
		moves.put("O  XXOO X", new int[] {2, 1});
		moves.put("O OXXOOXX", new int[] {0, 1});
		moves.put("O  OXOXOX", new int[] {0, 2});
		moves.put("X O O XO ", new int[] {1, 0});
		moves.put(" XX XOO O", new int[] {0, 0});
		moves.put("XOXOX O  ", new int[] {2, 2});
		moves.put("XOOOX OX ", new int[] {2, 2});
		moves.put("OO XXOOX ", new int[] {0, 2});
		moves.put("X   XOOXO", new int[] {0, 1});
		moves.put("  O XOO X", new int[] {0, 0});
		moves.put("OO XXOOXX", new int[] {0, 2});
		moves.put("O OOXXXXO", new int[] {0, 1});
		moves.put("X  OOXO  ", new int[] {0, 2});
		moves.put("X XOOXOO ", new int[] {0, 1});
		moves.put("OOXXXOO  ", new int[] {2, 2});
		moves.put("X  OOX  O", new int[] {0, 2});
		moves.put("X XOOXO O", new int[] {0, 1});
		moves.put("XO  O  XO", new int[] {2, 0});
		moves.put("XO OO XXO", new int[] {1, 2});
		moves.put("OOX X  OX", new int[] {1, 2});
		moves.put("X OOXXOXO", new int[] {0, 1});
		moves.put("   OX XOO", new int[] {0, 2});
		moves.put("OO OX X  ", new int[] {0, 2});
		moves.put("  X XO OO", new int[] {2, 0});
		moves.put("XOX O OXO", new int[] {1, 0});
		moves.put(" O OXXOOX", new int[] {0, 2});
		moves.put("XO OXOOX ", new int[] {2, 2});
		moves.put("X XOX O O", new int[] {0, 1});
		moves.put("O   XXO O", new int[] {1, 0});
		moves.put("OXO XXXOO", new int[] {1, 0});
		moves.put("X OOO X  ", new int[] {1, 2});
		moves.put("XX  O  OO", new int[] {0, 2});
		moves.put("XOO O XXO", new int[] {1, 0});
		moves.put("OXO XO  X", new int[] {2, 1});
		moves.put(" OO XXX O", new int[] {1, 0});
		moves.put(" OX X OXO", new int[] {1, 2});
		moves.put(" OXOXXOXO", new int[] {0, 0});
		moves.put("X  XOOO  ", new int[] {0, 2});
		moves.put("X XXOOO O", new int[] {0, 1});
		moves.put("X OOOXXO ", new int[] {0, 1});
		moves.put("OO  XO XX", new int[] {2, 0});
		moves.put("OOX XXOXO", new int[] {1, 0});
		moves.put("OO OXXXO ", new int[] {0, 2});
		moves.put("O  OXO XX", new int[] {2, 0});
		moves.put("O OXX XO ", new int[] {1, 2});
		moves.put("X OOOXX O", new int[] {0, 1});
		moves.put("OXO XO   ", new int[] {2, 1});
		moves.put("XOOOOX X ", new int[] {2, 0});
		moves.put("XO OOXOX ", new int[] {0, 2});
		moves.put("XOOOX  XO", new int[] {1, 2});
		moves.put("XX  OO O ", new int[] {0, 2});
		moves.put("O  XXOOXO", new int[] {0, 1});
		moves.put("XOXOO  XO", new int[] {1, 2});
		moves.put("XX OOX OO", new int[] {0, 2});
		moves.put(" O OXXOXO", new int[] {0, 0});
		moves.put("X XOOX OO", new int[] {0, 1});
		moves.put("  XOX OXO", new int[] {0, 1});
		moves.put(" OO XXXOO", new int[] {1, 0});
		moves.put("O OOXXX O", new int[] {0, 1});
		moves.put("XXO O XOO", new int[] {1, 0});
		moves.put("X XOX OO ", new int[] {0, 1});
		moves.put("X XXOOOO ", new int[] {0, 1});
		moves.put("XO OXXO O", new int[] {2, 1});
		moves.put("XOXXOOO  ", new int[] {2, 1});
		moves.put("XOO XX OO", new int[] {1, 0});
		moves.put("XOO OOXX ", new int[] {2, 2});
		moves.put("O  XXOOOX", new int[] {0, 2});
		moves.put("O OXX OOX", new int[] {1, 2});
		moves.put(" OO XXOXO", new int[] {1, 0});
		moves.put("X X O  OO", new int[] {0, 1});
		moves.put("OOX XOOX ", new int[] {1, 0});
		moves.put("OOX XOO X", new int[] {1, 0});
		moves.put(" O OXXXOO", new int[] {0, 2});
		moves.put(" OXOXO XO", new int[] {2, 0});
		moves.put("XOOXOO X ", new int[] {2, 0});
		moves.put("XXO OOXO ", new int[] {1, 0});
		moves.put("XX  O OO ", new int[] {0, 2});
		moves.put("XO XOOOX ", new int[] {0, 2});
		moves.put("OOXXXOOX ", new int[] {2, 2});
		moves.put("XOOOXX O ", new int[] {2, 2});
		moves.put("OO OXX OX", new int[] {0, 2});
		moves.put("XOXOOXO  ", new int[] {2, 2});
		moves.put("XOXOOX  O", new int[] {2, 1});
		moves.put("OXO XOO X", new int[] {2, 1});
		moves.put("XO  OOXXO", new int[] {1, 0});
	}
	if (_symbol=='O') {
		moves.put("     X   ", new int[] {1, 1});
		moves.put("X   OX   ", new int[] {2, 1});
		moves.put("X   OXXO ", new int[] {0, 1});
		moves.put("         ", new int[] {1, 1});
		moves.put("X   O    ", new int[] {2, 2});
		moves.put("X   OX  O", new int[] {2, 1});
		moves.put("X X OX OO", new int[] {2, 0});
		moves.put("XX  OX O ", new int[] {0, 2});
		moves.put("XXO OX OX", new int[] {2, 0});
		moves.put("X   O  XO", new int[] {1, 2});
		moves.put("XX  OO XO", new int[] {1, 0});
		moves.put(" X       ", new int[] {1, 1});
		moves.put(" X  O   X", new int[] {1, 2});
		moves.put("XX  OO  X", new int[] {1, 0});
		moves.put("    O  X ", new int[] {0, 0});
		moves.put("O   O XX ", new int[] {2, 2});
		moves.put("    OXX  ", new int[] {2, 1});
		moves.put("  X OXXO ", new int[] {0, 1});
		moves.put("  X O    ", new int[] {2, 0});
		moves.put("  XXO O  ", new int[] {2, 1});
		moves.put("  XXO OOX", new int[] {0, 1});
		moves.put("XXOXOX O ", new int[] {2, 0});
		moves.put("    O   X", new int[] {0, 0});
		moves.put("O X O   X", new int[] {1, 2});
		moves.put("OXX OO  X", new int[] {1, 0});
		moves.put("       X ", new int[] {1, 1});
		moves.put("  X O  X ", new int[] {1, 2});
		moves.put("X X OO X ", new int[] {1, 0});
		moves.put("    OX   ", new int[] {0, 0});
		moves.put("O  XOX   ", new int[] {2, 2});
		moves.put("        X", new int[] {1, 1});
		moves.put(" XX OO  X", new int[] {1, 0});
		moves.put("O X O  X ", new int[] {2, 2});
		moves.put("    O X X", new int[] {2, 1});
		moves.put(" X  O XOX", new int[] {1, 2});
		moves.put("XX  OOXOX", new int[] {1, 0});
		moves.put("O   OX X ", new int[] {2, 2});
		moves.put("X        ", new int[] {1, 1});
		moves.put("X   O X  ", new int[] {1, 0});
		moves.put("X  OO X X", new int[] {1, 2});
		moves.put("O   O  XX", new int[] {2, 0});
		moves.put("OX  O OXX", new int[] {1, 0});
		moves.put("      X  ", new int[] {1, 1});
		moves.put("    O XX ", new int[] {2, 2});
		moves.put("  X O XXO", new int[] {0, 0});
		moves.put("O   OX  X", new int[] {0, 2});
		moves.put("O O OXX X", new int[] {0, 1});
		moves.put("    X    ", new int[] {0, 0});
		moves.put("O X X    ", new int[] {2, 0});
		moves.put("OXX X O  ", new int[] {1, 0});
		moves.put("X  XO   O", new int[] {2, 0});
		moves.put("X  XO OXO", new int[] {0, 2});
		moves.put("OX  X    ", new int[] {2, 1});
		moves.put("OX XX  O ", new int[] {1, 2});
		moves.put("OX XXO OX", new int[] {0, 2});
		moves.put("O X OX   ", new int[] {2, 2});
		moves.put("  X      ", new int[] {1, 1});
		moves.put("X X O    ", new int[] {0, 1});
		moves.put("XOX O  X ", new int[] {1, 2});
		moves.put("XOX OOXX ", new int[] {1, 0});
		moves.put("   XO    ", new int[] {0, 0});
		moves.put("OX XO    ", new int[] {2, 2});
		moves.put(" X  OX   ", new int[] {2, 2});
		moves.put(" X  OXX O", new int[] {0, 0});
		moves.put("O   X X  ", new int[] {0, 2});
		moves.put("O O X X X", new int[] {0, 1});
		moves.put(" X  O  X ", new int[] {1, 2});
		moves.put("XX  OO X ", new int[] {1, 0});
		moves.put("O   OXOXX", new int[] {1, 0});
		moves.put(" XX O    ", new int[] {0, 0});
		moves.put("OXX O   X", new int[] {1, 2});
		moves.put("OXXXOO  X", new int[] {2, 0});
		moves.put("  X OXO  ", new int[] {2, 2});
		moves.put("  X OXOXO", new int[] {0, 0});
		moves.put("X   O  X ", new int[] {1, 2});
		moves.put("O  XO X  ", new int[] {2, 2});
		moves.put("X  OO XX ", new int[] {1, 2});
		moves.put("O XXO    ", new int[] {2, 2});
		moves.put("OXX O  X ", new int[] {2, 2});
		moves.put("XX  O   O", new int[] {0, 2});
		moves.put("XXOXO   O", new int[] {1, 2});
		moves.put("  X O   X", new int[] {1, 2});
		moves.put("X X OO  X", new int[] {1, 0});
		moves.put(" XX OX  O", new int[] {0, 0});
		moves.put("X   O   X", new int[] {1, 2});
		moves.put(" X  O    ", new int[] {0, 0});
		moves.put("OX  O  X ", new int[] {2, 2});
		moves.put("OXO X X  ", new int[] {2, 1});
		moves.put("OXO XXXO ", new int[] {1, 0});
		moves.put("OX  O X  ", new int[] {2, 2});
		moves.put("   XO   X", new int[] {2, 1});
		moves.put("X  XO  OX", new int[] {0, 1});
		moves.put("X  XOO XO", new int[] {0, 2});
		moves.put("X  XOO  X", new int[] {2, 0});
		moves.put("XX XOOO X", new int[] {0, 2});
		moves.put(" X XOO  X", new int[] {2, 0});
		moves.put(" XXXOOO X", new int[] {0, 0});
		moves.put(" X  O XXO", new int[] {0, 0});
		moves.put("O  XO   X", new int[] {0, 1});
		moves.put("OOXXO   X", new int[] {2, 1});
		moves.put("    OX X ", new int[] {2, 2});
		moves.put(" X  OX XO", new int[] {0, 0});
		moves.put("    O X  ", new int[] {0, 2});
		moves.put("X O O X  ", new int[] {1, 0});
		moves.put("X OOO X X", new int[] {1, 2});
		moves.put("   XOX OX", new int[] {0, 1});
		moves.put("X X O   O", new int[] {0, 1});
		moves.put("XOX O X O", new int[] {2, 1});
		moves.put("   XOX   ", new int[] {2, 1});
		moves.put("   XOXXO ", new int[] {0, 1});
		moves.put("O   X   X", new int[] {0, 2});
		moves.put("OXO X   X", new int[] {2, 1});
		moves.put("OXO XX OX", new int[] {1, 0});
		moves.put("X X OXO O", new int[] {2, 1});
		moves.put("X  XO    ", new int[] {2, 0});
		moves.put("X  XOXO  ", new int[] {0, 2});
		moves.put("OXO OX  X", new int[] {2, 0});
		moves.put(" X  O X  ", new int[] {1, 2});
		moves.put("XX  OOX  ", new int[] {1, 0});
		moves.put("XX  O    ", new int[] {0, 2});
		moves.put("XXO OX   ", new int[] {2, 0});
		moves.put(" XX O O  ", new int[] {0, 0});
		moves.put("OXX OXO  ", new int[] {1, 0});
		moves.put("  XXO    ", new int[] {2, 1});
		moves.put("  XXO XO ", new int[] {0, 1});
		moves.put(" X  OOXX ", new int[] {1, 0});
		moves.put("  OXO X  ", new int[] {0, 0});
		moves.put("O OXOXX  ", new int[] {0, 1});
		moves.put("X X OX O ", new int[] {0, 1});
		moves.put("OX  O   X", new int[] {1, 0});
		moves.put("OX OOX  X", new int[] {2, 0});
		moves.put("   X     ", new int[] {1, 1});
		moves.put("   XO X  ", new int[] {0, 0});
		moves.put("O  XO XX ", new int[] {2, 2});
		moves.put("   XO XXO", new int[] {0, 0});
		moves.put("O X OO XX", new int[] {1, 0});
		moves.put("O  XO OXX", new int[] {0, 2});
		moves.put("OXX OOX X", new int[] {1, 0});
		moves.put("XXO OX  O", new int[] {2, 0});
		moves.put("XOX O   X", new int[] {2, 1});
		moves.put("X  XOXO O", new int[] {2, 1});
		moves.put("X  XOO X ", new int[] {2, 0});
		moves.put("X XXOOOX ", new int[] {0, 1});
		moves.put("O O OX XX", new int[] {0, 1});
		moves.put("X   OO XX", new int[] {1, 0});
		moves.put("O   X  X ", new int[] {0, 1});
		moves.put("OO XX  X ", new int[] {0, 2});
		moves.put("OO XOX  X", new int[] {0, 2});
		moves.put("XXOXO    ", new int[] {2, 0});
		moves.put("X X O O  ", new int[] {0, 1});
		moves.put("XOXXO O  ", new int[] {2, 1});
		moves.put("X  XO OX ", new int[] {0, 2});
		moves.put("OXX O X  ", new int[] {2, 2});
		moves.put("  X O X  ", new int[] {1, 2});
		moves.put("X X OOX  ", new int[] {1, 0});
		moves.put("  XXOXOO ", new int[] {2, 2});
		moves.put("   XO  X ", new int[] {2, 2});
		moves.put("   XOX XO", new int[] {0, 0});
		moves.put("  X O O X", new int[] {1, 2});
		moves.put("X X OOO X", new int[] {1, 0});
		moves.put(" X  OO XX", new int[] {1, 0});
		moves.put("  X O OX ", new int[] {1, 0});
		moves.put("  XOOXOX ", new int[] {0, 0});
		moves.put("    O  XX", new int[] {2, 0});
		moves.put("    OXOXX", new int[] {0, 2});
		moves.put("OO XO  XX", new int[] {0, 2});
		moves.put("  X OX   ", new int[] {2, 2});
		moves.put("X X OX  O", new int[] {0, 1});
		moves.put("XOXXOX  O", new int[] {2, 1});
		moves.put("O   XX   ", new int[] {1, 0});
		moves.put("OX OXX   ", new int[] {2, 0});
		moves.put("  O OXX  ", new int[] {0, 1});
		moves.put(" OO OXXX ", new int[] {0, 0});
		moves.put("OXX O    ", new int[] {2, 2});
		moves.put("X  XOX O ", new int[] {0, 1});
		moves.put(" X XO    ", new int[] {0, 0});
		moves.put("OX XO  X ", new int[] {2, 2});
		moves.put("X OOOXX  ", new int[] {2, 1});
		moves.put("X OOOXXOX", new int[] {0, 1});
		moves.put("X  XOOOXX", new int[] {0, 2});
		moves.put("O  XO  X ", new int[] {2, 2});
		moves.put("X XXO O  ", new int[] {0, 1});
		moves.put("XOXXOXO  ", new int[] {2, 1});
		moves.put(" XXXO OO ", new int[] {2, 2});
		moves.put("O X X O X", new int[] {1, 0});
		moves.put("XXO O   X", new int[] {2, 0});
		moves.put("O OXOX  X", new int[] {0, 1});
		moves.put("XOXXO OX ", new int[] {2, 2});
		moves.put("    OX  X", new int[] {0, 2});
		moves.put(" XO OX  X", new int[] {2, 0});
		moves.put("XXOOO X  ", new int[] {1, 2});
		moves.put("  XXO  XO", new int[] {0, 0});
		moves.put("X   O X O", new int[] {1, 0});
		moves.put("XX OO X O", new int[] {1, 2});
		moves.put("X   OOXX ", new int[] {1, 0});
		moves.put("OX  OX   ", new int[] {2, 2});
		moves.put("X XOO X O", new int[] {1, 2});
		moves.put("  O OXX X", new int[] {2, 1});
		moves.put(" XO OXXOX", new int[] {0, 0});
		moves.put("XX OO X  ", new int[] {1, 2});
		moves.put("X X OO XO", new int[] {1, 0});
		moves.put(" X XO  OX", new int[] {0, 2});
		moves.put("XXOXO  OX", new int[] {2, 0});
		moves.put("X   OX OX", new int[] {0, 1});
		moves.put("XOX OX XO", new int[] {2, 0});
		moves.put("OX OO X X", new int[] {1, 2});
		moves.put("  X OO XX", new int[] {1, 0});
		moves.put("XX  OX  O", new int[] {0, 2});
		moves.put("XXO OX XO", new int[] {2, 0});
		moves.put(" XX OOX  ", new int[] {1, 0});
		moves.put(" XO O X  ", new int[] {1, 2});
		moves.put(" XO OOX X", new int[] {1, 0});
		moves.put("  XXOXO O", new int[] {2, 1});
		moves.put(" X  OOX X", new int[] {1, 0});
		moves.put("O   OXX  ", new int[] {2, 2});
		moves.put("  XXO  OX", new int[] {0, 1});
		moves.put("  OXOX  X", new int[] {2, 0});
		moves.put("X   OOXXO", new int[] {1, 0});
		moves.put("X  XO O X", new int[] {0, 2});
		moves.put("OXXXO    ", new int[] {2, 2});
		moves.put(" XO OOXX ", new int[] {1, 0});
		moves.put("XXO OOX  ", new int[] {1, 0});
		moves.put("  X OOOXX", new int[] {1, 0});
		moves.put("O  XO X X", new int[] {2, 1});
		moves.put("OX XO XOX", new int[] {0, 2});
		moves.put("O X OOX X", new int[] {1, 0});
		moves.put("O  OXX  X", new int[] {2, 0});
		moves.put("  O O X X", new int[] {2, 1});
		moves.put("  O OXXOX", new int[] {0, 1});
		moves.put("X O OX  X", new int[] {2, 0});
		moves.put("XXOXOX  O", new int[] {2, 0});
		moves.put("OO XO X X", new int[] {0, 2});
		moves.put(" XOXO XOX", new int[] {0, 0});
		moves.put("O OXX   X", new int[] {0, 1});
		moves.put("OX XO   X", new int[] {2, 0});
		moves.put("OX XO OXX", new int[] {0, 2});
		moves.put(" XX OO X ", new int[] {1, 0});
		moves.put("O  XOXX  ", new int[] {2, 2});
		moves.put("O  XX    ", new int[] {1, 2});
		moves.put("O  XXO X ", new int[] {0, 1});
		moves.put("OOXXXO X ", new int[] {2, 0});
		moves.put("  XXOX O ", new int[] {0, 1});
		moves.put("    OXXOX", new int[] {0, 1});
		moves.put(" XXOO OX ", new int[] {1, 2});
		moves.put("OXXXO O X", new int[] {1, 2});
		moves.put("   XO XOX", new int[] {0, 1});
		moves.put(" X  OXXO ", new int[] {0, 0});
		moves.put("OXX OXXO ", new int[] {2, 2});
		moves.put("  XXOOX  ", new int[] {0, 0});
		moves.put("O XXOOXX ", new int[] {2, 2});
		moves.put("OXX O OX ", new int[] {1, 0});
		moves.put("O XXOOX X", new int[] {2, 1});
		moves.put("OXX OX   ", new int[] {2, 2});
		moves.put("  O O XX ", new int[] {2, 2});
		moves.put("X O O XXO", new int[] {1, 2});
		moves.put("XOXXO    ", new int[] {2, 1});
		moves.put("X XXO O O", new int[] {2, 1});
		moves.put("O   O X X", new int[] {2, 1});
		moves.put("O X O XOX", new int[] {0, 1});
		moves.put("  X O OXX", new int[] {1, 2});
		moves.put("X X OOOXX", new int[] {1, 0});
		moves.put("X OOO XX ", new int[] {1, 2});
		moves.put(" XO O XXO", new int[] {1, 2});
		moves.put("    OXXXO", new int[] {0, 0});
		moves.put("O XOXX   ", new int[] {2, 0});
		moves.put("X  OO XXO", new int[] {1, 2});
		moves.put("OX XO X  ", new int[] {2, 2});
		moves.put("X XOO X  ", new int[] {1, 2});
		moves.put("  X O XOX", new int[] {0, 1});
		moves.put("O  XO XOX", new int[] {0, 1});
		moves.put("  XOO OXX", new int[] {1, 2});
		moves.put("  X OOXX ", new int[] {1, 0});
		moves.put("O O XX  X", new int[] {0, 1});
		moves.put(" XX OXO O", new int[] {2, 1});
		moves.put("OOX X  X ", new int[] {2, 0});
		moves.put("OOXXX OX ", new int[] {1, 2});
		moves.put("OX XXO   ", new int[] {2, 1});
		moves.put("  X OOX X", new int[] {1, 0});
		moves.put("OX OO  XX", new int[] {1, 2});
		moves.put("XOX O X  ", new int[] {2, 1});
		moves.put("XOX O  XO", new int[] {1, 2});
		moves.put("XOXXOO XO", new int[] {2, 0});
		moves.put("X   O OXX", new int[] {0, 2});
		moves.put("XOO OXX  ", new int[] {2, 1});
		moves.put("X   OX XO", new int[] {2, 0});
		moves.put("XX  OXOXO", new int[] {0, 2});
		moves.put("OXX O O X", new int[] {1, 0});
		moves.put("X XXO  O ", new int[] {0, 1});
		moves.put("  X OX XO", new int[] {0, 0});
		moves.put(" X XOX O ", new int[] {2, 2});
		moves.put(" X XOXXOO", new int[] {0, 0});
		moves.put(" OOXOXX  ", new int[] {0, 0});
		moves.put("XX XOX OO", new int[] {2, 0});
		moves.put("O XXO XOX", new int[] {0, 1});
		moves.put("XXO O X O", new int[] {1, 2});
		moves.put("OXXOO   X", new int[] {1, 2});
		moves.put(" X  O OXX", new int[] {0, 2});
		moves.put("  XXOOOXX", new int[] {0, 0});
		moves.put("O OXX X  ", new int[] {0, 1});
		moves.put("OX  O XOX", new int[] {1, 2});
		moves.put("OXX OOXOX", new int[] {1, 0});
		moves.put("XOX OXO  ", new int[] {2, 1});
		moves.put(" XXXO  O ", new int[] {0, 0});
		moves.put("OXXXOX O ", new int[] {2, 2});
		moves.put(" XOXOOX  ", new int[] {2, 2});
		moves.put("X   O XOX", new int[] {0, 1});
		moves.put(" X XOOX  ", new int[] {0, 0});
		moves.put("OX XOOXX ", new int[] {2, 2});
		moves.put("XOXXOO X ", new int[] {2, 0});
		moves.put("OXX X  O ", new int[] {2, 0});
		moves.put("OXXXX OO ", new int[] {2, 2});
		moves.put("O  XOXXOX", new int[] {0, 1});
		moves.put("OX  OXXOX", new int[] {0, 2});
		moves.put("  XXOOO X", new int[] {2, 1});
		moves.put(" XXXOOOOX", new int[] {0, 0});
		moves.put(" X XOX  O", new int[] {0, 0});
		moves.put("XX XO O O", new int[] {2, 1});
		moves.put("XOX O OX ", new int[] {1, 2});
		moves.put("XOXXOOOX ", new int[] {2, 2});
		moves.put("  XXOX  O", new int[] {0, 0});
		moves.put("X   O XXO", new int[] {1, 0});
		moves.put("XX OO XXO", new int[] {1, 2});
		moves.put("O XXXO   ", new int[] {2, 0});
		moves.put("OXXXXOO  ", new int[] {2, 1});
		moves.put("XXO O X  ", new int[] {1, 0});
		moves.put("XXOOO XX ", new int[] {1, 2});
		moves.put("  XXOO  X", new int[] {2, 1});
		moves.put(" XXXOO OX", new int[] {0, 0});
		moves.put("O X XXO  ", new int[] {1, 0});
		moves.put("X  OOXX  ", new int[] {2, 1});
		moves.put("X XOOXXO ", new int[] {0, 1});
		moves.put(" X XO  XO", new int[] {0, 0});
		moves.put("  O OXXXO", new int[] {0, 0});
		moves.put("XOX O O X", new int[] {2, 1});
		moves.put("O X O OXX", new int[] {1, 0});
		moves.put("  XXOOXOX", new int[] {0, 1});
		moves.put("XOXXO O X", new int[] {2, 1});
		moves.put("OXXXO O  ", new int[] {2, 2});
		moves.put("OX XOXO X", new int[] {0, 2});
		moves.put("XXOOO X X", new int[] {1, 2});
		moves.put("X   OXXOO", new int[] {0, 1});
		moves.put("X  XO  XO", new int[] {2, 0});
		moves.put("X XXO OXO", new int[] {0, 1});
		moves.put("OX  XX O ", new int[] {1, 0});
		moves.put("OX OXX OX", new int[] {2, 0});
		moves.put("X O OXXOX", new int[] {0, 1});
		moves.put("O  OXX X ", new int[] {2, 0});
		moves.put("  OXO XXO", new int[] {1, 2});
		moves.put("X X OXOXO", new int[] {0, 1});
		moves.put("XXO O  X ", new int[] {2, 0});
		moves.put("XOX OO XX", new int[] {1, 0});
		moves.put("OX XOX   ", new int[] {2, 2});
		moves.put("O XXOO  X", new int[] {2, 1});
		moves.put("OXXXOO OX", new int[] {2, 0});
		moves.put("XOXXO   O", new int[] {2, 1});
		moves.put("O O XXX  ", new int[] {0, 1});
		moves.put("OX XOOXOX", new int[] {0, 2});
		moves.put(" XXXOX OO", new int[] {2, 0});
		moves.put("XOX OOXXO", new int[] {1, 0});
		moves.put("OX  X XO ", new int[] {0, 2});
		moves.put("OO XXOXX ", new int[] {0, 2});
		moves.put("  XXOO X ", new int[] {0, 0});
		moves.put("O XXOO XX", new int[] {2, 0});
		moves.put("X XXO OO ", new int[] {2, 2});
		moves.put("O O X XX ", new int[] {0, 1});
		moves.put("  OXOXXOX", new int[] {0, 1});
		moves.put("OXXXOOX  ", new int[] {2, 2});
		moves.put("XX XO OXO", new int[] {0, 2});
		moves.put(" X XOO X ", new int[] {2, 2});
		moves.put(" XXXOO XO", new int[] {0, 0});
		moves.put("X XXOO OX", new int[] {0, 1});
		moves.put("O XXO X  ", new int[] {2, 2});
		moves.put("OXOXX XO ", new int[] {1, 2});
		moves.put("X O O XOX", new int[] {0, 1});
		moves.put("X  OOXX O", new int[] {2, 1});
		moves.put("X XOOXXOO", new int[] {0, 1});
		moves.put("X  XOXOXO", new int[] {0, 2});
		moves.put("O X X OX ", new int[] {1, 0});
		moves.put(" OO OXX X", new int[] {0, 0});
		moves.put("OXOXO X  ", new int[] {2, 2});
		moves.put("OXXXO XO ", new int[] {2, 2});
		moves.put("XX OOXXO ", new int[] {0, 2});
		moves.put("O   OXXOX", new int[] {0, 1});
		moves.put("  X OXX O", new int[] {0, 0});
		moves.put("XX OOXXOO", new int[] {0, 2});
		moves.put("X XXOOOOX", new int[] {0, 1});
		moves.put("O  XXOX  ", new int[] {0, 2});
		moves.put("O OXXOXX ", new int[] {0, 1});
		moves.put("XXOOOXX  ", new int[] {2, 2});
		moves.put("O  XXO  X", new int[] {0, 2});
		moves.put("O OXXOX X", new int[] {0, 1});
		moves.put("OX  X  OX", new int[] {2, 0});
		moves.put("OX XX OOX", new int[] {1, 2});
		moves.put("XXO O  XO", new int[] {1, 2});
		moves.put("O XXOOXOX", new int[] {0, 1});
		moves.put("   XO OXX", new int[] {0, 2});
		moves.put("XX XO O  ", new int[] {0, 2});
		moves.put("  O OX XX", new int[] {2, 0});
		moves.put("OXO X XOX", new int[] {1, 0});
		moves.put(" X XOOXXO", new int[] {0, 2});
		moves.put("OX XOXXO ", new int[] {2, 2});
		moves.put("O OXO X X", new int[] {0, 1});
		moves.put("X   OOX X", new int[] {1, 0});
		moves.put("XOX OOOXX", new int[] {1, 0});
		moves.put("O XXX O  ", new int[] {1, 2});
		moves.put("OO  X  XX", new int[] {0, 2});
		moves.put("OXX X OOX", new int[] {1, 0});
		moves.put("XOX OX  O", new int[] {2, 1});
		moves.put(" XX OOO X", new int[] {1, 0});
		moves.put(" XO O XOX", new int[] {1, 2});
		moves.put(" XOXOOXOX", new int[] {0, 0});
		moves.put("O  OXXX  ", new int[] {0, 2});
		moves.put("O OOXXX X", new int[] {0, 1});
		moves.put("O XXXOOX ", new int[] {0, 1});
		moves.put("XX  OX OO", new int[] {2, 0});
		moves.put("XXO OOXOX", new int[] {1, 0});
		moves.put("XX XOOOX ", new int[] {0, 2});
		moves.put("X  XOX OO", new int[] {2, 0});
		moves.put("X XOO OX ", new int[] {1, 2});
		moves.put("O XXXOO X", new int[] {0, 1});
		moves.put("XOX OX   ", new int[] {2, 1});
		moves.put("OXXXXO O ", new int[] {2, 0});
		moves.put("OX XXOXO ", new int[] {0, 2});
		moves.put("OXXXO  OX", new int[] {1, 2});
		moves.put("OO  XX X ", new int[] {0, 2});
		moves.put("X  OOXXOX", new int[] {0, 1});
		moves.put("OXOXX  OX", new int[] {1, 2});
		moves.put("OO XXO XX", new int[] {0, 2});
		moves.put(" X XOOXOX", new int[] {0, 0});
		moves.put("O OXXO XX", new int[] {0, 1});
		moves.put("  OXO XOX", new int[] {0, 1});
		moves.put(" XX OOOXX", new int[] {1, 0});
		moves.put("X XXOOO X", new int[] {0, 1});
		moves.put("OOX X OXX", new int[] {1, 0});
		moves.put("O OXO XX ", new int[] {0, 1});
		moves.put("O OOXXXX ", new int[] {0, 1});
		moves.put("OX XOOX X", new int[] {2, 1});
		moves.put("OXOOXXX  ", new int[] {2, 1});
		moves.put("OXX OO XX", new int[] {1, 0});
		moves.put("OXX XXOO ", new int[] {2, 2});
		moves.put("X  OOXXXO", new int[] {0, 2});
		moves.put("X XOO XXO", new int[] {1, 2});
		moves.put(" XX OOXOX", new int[] {1, 0});
		moves.put("O O X  XX", new int[] {0, 1});
		moves.put("XXO OXXO ", new int[] {1, 0});
		moves.put("XXO OXX O", new int[] {1, 0});
		moves.put(" X XOOOXX", new int[] {0, 2});
		moves.put(" XOXOX OX", new int[] {2, 0});
		moves.put("OXXOXX O ", new int[] {2, 0});
		moves.put("OOX XXOX ", new int[] {1, 0});
		moves.put("OO  X XX ", new int[] {0, 2});
		moves.put("OX OXXXO ", new int[] {0, 2});
		moves.put("XXOOOXXO ", new int[] {2, 2});
		moves.put("OXXXOO X ", new int[] {2, 2});
		moves.put("XX XOO XO", new int[] {0, 2});
		moves.put("OXOXXOX  ", new int[] {2, 2});
		moves.put("OXOXXO  X", new int[] {2, 1});
		moves.put("XOX OXX O", new int[] {2, 1});
		moves.put("OX  XXOOX", new int[] {1, 0});
	}
    }

    public char getSymbol()
    {
	return _symbol;
    }

    public String getName()
    {
	return _name;
    }

    public int[] makeAMove(Board boardObj)
    {
	char   startingPlayer = Tournament.getStartingPlayer(); // symbol of starting player
	int[]  oppLastMove = boardObj.getLastMove(); // where the opponent moved to last
	int    oppLastRow = -1, oppLastCol = -1; // row and column of opponent's last move

	if (oppLastMove != null)  // there is a last move from the opponent
	    {
		oppLastRow = oppLastMove[0];
		oppLastCol = oppLastMove[1]; 
	    } // else I'm making the first move, the opponent couldn't have made a move

	//----------------------------
	// accessing the board obj
	// boardObj.isEmpty(row, col)   returns whether the cell is empty
	// boardObj.getCell(row, col)   returns the content of the cell
	//----------------------------

	int    myRow = 0, myCol = 0;  // row and column of my move
	char   mySymbol = _symbol;    // my symbol
	char   oppSymbol;             // opponent's symbol    
	if (mySymbol == 'X')          // find the opponent's symbol
	    oppSymbol = 'O';
	else
	    oppSymbol = 'X';

	char[][] board = boardObj.getBoard(); // board in 2D array
	
	turn = getTurn(board);

	// **** add instructions for my strategy to decide myRow and myCol






	// return my move (myRow, myCol) as the last step
	return moves.get(boardToString(board));
//	int[] myMove = new int[] {myRow, myCol};
//	return myMove;
    }

    public static String boardToString(char[][] board) {
    	String result = "";
    	for (char[] row: board) for (char symbol: row) result+=symbol;
    	return result;
    }
    
    public static int getTurn(char[][] board) {
    	int turn=0;
    	for (char[] row: board) for (char symbol: row) if (symbol=='O' || symbol=='X') turn++;
    	return turn;
    }
}